#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include <fcntl.h>

int main(int argc, char**  argv){
    printf("--------KILLING ANY WTFserver PROCESSES STILL RUNNING--------\n");
    system("killall -SIGINT WTFserver");
    printf("--------BEGINNING TEST CASES--------\n");  
    printf("tester-> Test 1: server fails to bind to specified port.\n");
    system("./WTFserver 0");
    printf("------------------------------------\n"); 

    printf("NOTE: For the remaining cases, we've used 39674 as the port. If, for some reason, binding to this port fails, please try again, or try replacing 39674 with a different port.\n");
    printf("------------------------------------\n"); 

    printf("tester-> Test 2: server binds to port, but client attempts to connect without configuring first.\n");
    system("./WTFserver 39674 &");
    system("./WTF create testproject");
    printf("------------------------------------\n"); 
    
    printf("tester-> Test 3: client configures IP address and port number properly.\n");
    system("./WTF configure localhost 39674");
    printf("tester-> Displaying the created .configure file:\n");
    system("cat client_folder/.configure");
    printf("\n");
    printf("------------------------------------\n"); 

    printf("tester-> Test 4: client creates a project called testproject.\n");
    system("./WTF create testproject");
    printf("tester-> Displaying the contents of testproject's parent directory on the client:\n");
    system("cd client_folder && ls");
    printf("tester-> Displaying the contents of testproject's parent directory on the server:\n");
    system("cd server_folder && ls");
    printf("tester-> Displaying the contents of testproject on the client:\n");
    system("cd client_folder/testproject && ls -a");
    printf("tester-> Displaying the contents of testproject on the server:\n");
    system("cd server_folder/testproject && ls -a");
    printf("tester-> Displaying the contents of testproject's .Manifest file on the client:\n");
    system("cat client_folder/testproject/.Manifest");
    printf("tester-> Displaying the contents of testproject's .Manifest file on the server:\n");
    system("cat server_folder/testproject/.Manifest");
    printf("------------------------------------\n"); 

    printf("tester-> Test 5: client attempts to create a project that already exists.\n");
    system("./WTF create testproject");
    printf("------------------------------------\n"); 

    printf("tester-> Test 6: client attempts to destroy a project that does not exist on the server.\n");
    system("./WTF destroy thisprojectdoesnotexist");
    printf("------------------------------------\n"); 

    printf("tester-> Test 7: client destroys the already-created testproject.\n");
    system("./WTF destroy testproject");
    printf("tester-> Attempting to cd into testproject on the server:\n");
    system("cd server_folder/testproject");
    printf("tester-> Displaying the contents of testproject on the client after calling destroy:\n");
    system("cd client_folder/testproject && ls  -a");
    printf("------------------------------------\n"); 

    printf("tester-> Test 8: client creates a different project.\n");
    system("./WTF create project");
    printf("tester-> Displaying the contents of project's parent directory on the client:\n");
    system("cd client_folder && ls");
    printf("tester-> Displaying the contents of project's parent directory on the server:\n");
    system("cd server_folder && ls");    
    printf("------------------------------------\n"); 
   
    printf("tester-> Test 9: client creates two files to add to project\n");
    int fp = open("./client_folder/project/helloWorld.c", O_WRONLY | O_CREAT | O_TRUNC, 0600);
    write(fp, "#include<stdio.h>\n#include<stdlib.h>\n\n", strlen("#include<stdio.h>\n#include<stdlib.h>\n\n"));
    write(fp, "int main(int argc, char** argv){\n\tprintf(\"Hello world!\");\n\treturn 0;\n}\n", strlen("int main(int argc, char** argv){\n\tprintf(\"Hello world!\");\n\treturn 0;\n}\n"));
    close(fp);
    int fp2 = open("./client_folder/project/CS214.txt", O_WRONLY | O_CREAT | O_TRUNC, 0600);
    write(fp2, "You've reached the end of CS214: Systems Programming!\n", strlen("You've reached the end of CS214: Systems Programming!\n"));
    close(fp2);
    printf("tester-> Displaying the contents of the first file (helloWorld.c):\n");
    system("cat client_folder/project/helloWorld.c");
    printf("tester-> Displaying the contents of the second file (CS214.txt):\n");
    system("cat client_folder/project/CS214.txt");
    printf("tester-> Adding helloWorld.c to project.\n");
    system("./WTF add project helloWorld.c");
    printf("tester-> Displaying client's .Manifest for project after adding helloWorld.c:\n");
    system("cat client_folder/project/.Manifest");
    printf("tester-> Adding CS214.txt to project.\n");
    system("./WTF add project CS214.txt");
    printf("tester-> Displaying client's .Manifest for project after adding CS214.txt:\n");
    system("cat client_folder/project/.Manifest");
    printf("tester-> Displaying server's .Manifest for project after the client added two files:\n");
    system("cat server_folder/project/.Manifest");
    printf("------------------------------------\n"); 

    printf("tester-> Test 10: client commits the two added files (this will output any changes that were made).\n");
    system("./WTF commit project");
    printf("tester-> Displaying client's .Commit file:\n");
    system("cat client_folder/project/.Commit");
    printf("tester-> Displaying server's .Commit file:\n");
    system("cat server_folder/project/.Commit");   
    printf("------------------------------------\n");  

    printf("tester-> Test 11: client pushes these changes to the server.\n");
    printf("tester-> Displaying contents of project on client before push:\n");
    system("cd client_folder/project && ls -a");
    printf("tester-> Displaying contents of project on server before push:\n");
    system("cd server_folder/project && ls -a");    
    printf("tester-> Displaying .Manifest on client before push:\n");
    system("cat client_folder/project/.Manifest");
    printf("tester-> Displaying .Manifest on server before push:\n");
    system("cat server_folder/project/.Manifest");
    printf("tester-> Pushing now.\n");
    system("./WTF push project");
    printf("tester-> Displaying contents of project on client after push:\n");
    system("cd client_folder/project && ls -a");
    printf("tester-> Displaying contents of project on server after push:\n");
    system("cd server_folder/project && ls -a");    
    printf("tester-> Displaying .Manifest on client after push:\n");
    system("cat client_folder/project/.Manifest");
    printf("tester-> Displaying .Manifest on server after push (message from server may appear first due to network latency. This is not part of the .Manifest file.):\n");
    sleep(0.5);
    system("cat server_folder/project/.Manifest");
    printf("------------------------------------\n"); 

    printf("tester-> Test 12: client removes a file, modifies a file, and adds a file, then commits the changes.\n");
    printf("tester-> displaying contents of project prior to any changes:\n");
    system("cd client_folder/project && ls -a");
    printf("tester-> running remove to remove CS214.txt from project");
    system("./WTF remove project CS214.txt");
    printf("tester-> displaying contents of project after removing CS214\n");
    printf("tester-> modifying helloWorld.txt\n");
    int fp3 = open("./client_folder/project/helloWorld.c", O_WRONLY | O_CREAT | O_TRUNC, 0600);
    write(fp3, "int main(int argc, char** argv){\n\tprintf(\"This has been modified!\");\n\treturn 0;\n}\n", strlen("int main(int argc, char** argv){\n\tprintf(\"This has been modified!\");\n\treturn 0;\n}\n"));
    close(fp3);
    printf("tester-> displaying modified helloWorld.c\n");
    system("cat client_folder/project/helloWorld.c");
    printf("tester-> creating a new file to be added to project.\n");
    int fp4 = open("./client_folder/project/newfile.txt", O_WRONLY | O_CREAT | O_TRUNC, 0600);
    write(fp4, "This is the new file that will be added to project.\n", strlen("This is the new file that will be added to project.\n"));
    close(fp4);
    printf("tester-> displaying the content of the new file (newfile.txt):\n");
    system("cat ./client_folder/project/newfile.txt");
    printf("tester-> adding newfile.txt to project.\n");
    system("./WTF add project newfile.txt");
    printf("tester-> committing changes.\n");
    system("./WTF commit project");
    printf("tester-> displaying the client's .Commit file:\n");
    system("cat client_folder/project/.Commit");
    printf("tester-> displaying the server's .Commit file:\n");
    system("cat server_folder/project/.Commit");
    printf("tester-> displaying the contents of project on client after commit:\n");
    system("cd client_folder/project && ls -a");
    printf("tester-> displaying the contents of project on server after commit:\n");
    system("cd server_folder/project && ls -a");
    printf("tester-> pushing new changes.\n");
    printf("tester-> Displaying contents of project on client before push:\n");
    system("cd client_folder/project && ls -a");
    printf("tester-> Displaying contents of project on server before push:\n");
    system("cd server_folder/project && ls -a");    
    printf("tester-> Displaying .Manifest on client before push:\n");
    system("cat client_folder/project/.Manifest");
    printf("tester-> Displaying .Manifest on server before push:\n");
    system("cat server_folder/project/.Manifest");
    printf("tester-> Pushing now.\n");
    system("./WTF push project");
    printf("tester-> Displaying contents of project on client after push:\n");
    system("cd client_folder/project && ls -a");
    printf("tester-> Displaying contents of project on server after push:\n");
    system("cd server_folder/project && ls -a");    
    printf("tester-> Displaying .Manifest on client after push:\n");
    system("cat client_folder/project/.Manifest");
    printf("tester-> Displaying .Manifest on server after push (message from server may appear first due to network latency. This is not part of the .Manifest file.):\n");
    sleep(0.5);
    system("cat server_folder/project/.Manifest");
    printf("------------------------------------\n"); 

    printf("tester-> Test 13: calling history on project.\n");
    printf("tester-> Requesting project history from server.\n");
    system("./WTF history project");
    printf("------------------------------------\n"); 

    printf("tester-> Test 14: calling currentversion on project.\n");
    printf("tester-> calling currentversion now.\n");
    system("./WTF currentversion project");
    printf("------------------------------------\n");

    printf("tester-> Test 15: deleting client project in order to be able to checkout from server.\n");
    system("rm -rf client_folder/project");
    printf("tester-> displaying content of project's parent directory after removing:\n");
    system("cd client_folder && ls");
    printf("tester-> requesting checkout from server.\n");
    system("./WTF checkout project");
    printf("tester-> displaying content of project's parent directory after checkout:\n");
    system("cd client_folder && ls");
    printf("tester-> displaying content of project after checkout.\n");
    system("cd client_folder/project && ls -a");
    printf("------------------------------------\n");     

    printf("tester-> Test 16: removing all files in client project in order to simulate having an older version than the server (and thus being able to update).\n");
    system("rm -rf client_folder/project");
    system("mkdir client_folder/project");
    int fp5 = open("./client_folder/project/.Manifest", O_WRONLY | O_CREAT | O_TRUNC, 0600);
    write(fp5, "1\n", strlen("1\n"));
    close(fp5);
    printf("tester-> displaying content of project after clearing it:\n");
    system("cd client_folder/project && ls -a");
    printf("tester-> displaying .Manifest of project (simulating an older version):\n");
    system("cat client_folder/project/.Manifest");
    printf("tester-> calling update.\n");
    system("./WTF update project");
    printf("tester-> displaying content of .Update file on client.\n");
    system("cat client_folder/project/.Update");
    printf("------------------------------------\n");

    printf("tester-> Test 17: requesting upgrade from server.\n");
    printf("tester-> displaying content of project before upgrade:\n");
    system("cd client_folder/project && ls -a");
    printf("tester-> displaying .Manifest of project before upgrade:\n");
    system("cat client_folder/project/.Manifest");     
    printf("tester-> calling upgrade.\n");
    system("./WTF upgrade project");
    printf("tester-> displaying content of project after upgrade:\n");
    system("cd client_folder/project && ls -a");
    printf("tester-> displaying .Manifest of project after upgrade:\n");
    system("cat client_folder/project/.Manifest"); 
    printf("------------------------------------\n");    

    printf("tester-> Test 18: rolling server back to an older version twice consecutively.\n");
    printf("tester-> displaying content of project on server before first rollback:\n");
    system("cd server_folder/project && ls -a");
    printf("tester-> displaying .Manifest of project on server before first rollback:\n");
    system("cat server_folder/project/.Manifest");
    printf("tester-> calling rollback from current version (3) to version 2.\n");
    system("./WTF rollback project 2");
    printf("tester-> displaying content of project on server after first rollback:\n");
    system("cd server_folder/project && ls -a");
    printf("tester-> displaying .Manifest of project on server after first rollback: (message from server may appear first due to network latency. This is not part of the .Manifest file.)\n");
    sleep(2);
    system("cat server_folder/project/.Manifest");
    printf("tester-> calling rollback from version 2 to version 1.\n");
    system("./WTF rollback project 1");
    printf("tester-> displaying content of project on server after second rollback:\n");
    system("cd server_folder/project && ls -a");
    printf("tester-> displaying .Manifest of project on server after second rollback: (message from server may appear first due to network latency. This is not part of the .Manifest file.)\n");
    sleep(2);
    system("cat server_folder/project/.Manifest");
    printf("------------------------------------\n");      
    
    printf("tester-> Test 19: failing upgrade and commit due to conflict.\n");
    printf("tester-> creating a new project for this test case, adding a file to it, committing, pushing file to server, modifying file, committing again, and pushing modification.\n");
    system("./WTF create conftest");
    int fp6 = open("./client_folder/conftest/test.txt", O_WRONLY | O_CREAT | O_TRUNC, 0600);
    write(fp6, "This is a test.\n", strlen("This is a test.\n"));
    close(fp6);
    system("./WTF add conftest test.txt");
    system("./WTF commit conftest");
    system("./WTF push conftest");
    sleep(1);
    system("cat server_folder/conftest/.Manifest");
    system("cp server_folder/conftest/.Manifest client_folder");
    int fp7 = open("./client_folder/conftest/test.txt", O_WRONLY | O_CREAT | O_TRUNC, 0600);
    write(fp7, "This has been modified.\n", strlen("This has been modified.\n"));
    close(fp7);
    system("./WTF commit conftest");
    system("./WTF push conftest");
    sleep(1);
    printf("tester-> Using temporarily stored .Manifest to simulate the client having an older project version.\n");
    system("rm -rf client_folder/conftest/.Manifest");
    system("cp client_folder/.Manifest client_folder/conftest");
    int fp8 = open("./client_folder/conftest/test.txt", O_WRONLY | O_CREAT | O_TRUNC, 0600);
    write(fp8, "This has been modified again.\n", strlen("This has been modified again.\n"));
    close(fp8);
    printf("tester-> calling update on conftest.\n");
    system("./WTF update conftest");
    printf("tester-> calling upgrade on conftest.\n");
    system("./WTF upgrade conftest");
    printf("tester-> calling commit on conftest.\n");
    system("./WTF commit conftest");
    sleep(1);
    printf("--------KILLING ANY WTFserver PROCESSES STILL RUNNING--------\n");
    system("killall -SIGINT WTFserver");
    printf("--------END OF TEST CASES--------\n");
    return 0;
}